version: "3.8"

services:
  quest-service:
    image: quest
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes: 
      - ./:/app
