version: "3.9"

services:
  postgres:
    image: postgres:13.3
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  questionare-service:
    image: questionare
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    entrypoint:
      - ./entrypoint.sh
    env_file:
      - .env
    depends_on:
      - postgres